### ISSUE TITLE
Improve Toast 

### ISSUE THREAD

**Issue by ksheetal** [ksheetal/TicTacToeGame#13]
Toast is working fine. if you can improve the color and icons then this issue is for you.

**Comment by kamontat** [comment]
I will take this :)

**Comment by ksheetal** [comment]
okay. all the best.

**Comment by kamontat** [comment]
Im not sure is that runnable or not #14. I didn't tried it.

**Comment by ksheetal** [comment]
Just give it a try. if it's not working check other issues.
