### ISSUE TITLE
New Screen for selecting [X or 0]

### ISSUE THREAD

**Issue by ksheetal** [ksheetal/TicTacToeGame#15]
New Screen where one can select if he wants to take X or O and after that game should start.

**Comment by lelloman** [comment]
Hi, can I pick this one up for Hacktoberfest?

**Comment by ksheetal** [comment]
Okay. All the best.

**Comment by lelloman** [comment]
Great, thanks. Just to be sure I understood the task, could you please confirm if this is what needs to be done: the game should be launched with a new Activity, X or 0 is selected, then the current Activity is started and player 1 will have the symbol selected in the previous Activity.

**Comment by ksheetal** [comment]
Yes, you are right.
