### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by ksheetal** [ksheetal/TicTacToeGame#16]
Simple Splash Screen with cool animation.

**Comment by Ruby6991** [comment]
Can I take this?

**Comment by ksheetal** [comment]
yes. all the best.

**Comment by TITANMQ** [comment]
Can I try it?

**Comment by ksheetal** [comment]
@Ruby6991  are you working on this?

**Comment by Ruby6991** [comment]
@ksheetal Yes. I'm almost done.

**Comment by TITANMQ** [comment]
@ksheetal If that is the case can I still pull request but don't accept mine so it still counts for Hacktoberfest?

**Comment by ksheetal** [comment]
@TITANMQ yes. you just need to create a pull request. and For the splash screen, I have updated the project files and there is no splash screen in that. if you want to work with that you can do that. please take a note that you can not use any third-party library this will just increase the APK size nothing else. A simple screen with little animation will do the job.
