### ISSUE TITLE
Update Read me file

### ISSUE THREAD

**Issue by ksheetal** [ksheetal/TicTacToeGame#3]

**Comment by AmanDeep9925** [comment]
What is the description for the readme.md can you please provide it.

**Comment by ksheetal** [comment]
I haven't made any readme for this. it's for Hacktoberfest. You just have to write good description for a tic-tac-toe game. It's for beginners.

**Comment by dangry** [comment]
Can I take this?

**Comment by ksheetal** [comment]
okay

**Comment by EmmanuelDemey** [comment]
You can use this amazing tool : https://github.com/kefranabg/readme-md-generator

**Comment by ksheetal** [comment]
@dangry @AmanDeep9925 anyone working on the readme?

**Comment by EkinEren** [comment]
@ksheetal I can work on this in case others aren't already

**Comment by ksheetal** [comment]
@EkinEren sure.

**Comment by ksheetal** [comment]
@EkinEren you working on read.me. Right?

**Comment by EkinEren** [comment]
@ksheetal yes, will try commit today. Sorry, I had some some workload at my job

**Comment by ksheetal** [comment]
@EkinEren No problem. I was just confirming. All the best.
