### ISSUE TITLE
Implement Timer

### ISSUE THREAD

**Issue by ksheetal** [ksheetal/TicTacToeGame#5]

**Comment by EkinEren** [comment]
@ksheetal heya, can I work on this issue?

**Comment by ksheetal** [comment]
okay

**Comment by dinesh-hd** [comment]
Can i get more specifics? 
1. Where does the timer have to be?
2. What is the timer used for?

**Comment by EkinEren** [comment]
@ksheetal should the timer reset after each round, or only when game is reset?
